USE [master]
GO

/****** Object:  Database [db_tiendavirtual]    Script Date: 7/10/2020 09:40:08 ******/
CREATE DATABASE [db_tiendavirtual]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_tiendavirtual', FILENAME = N'E:\Games\db_tiendavirtual.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db_tiendavirtual_log', FILENAME = N'E:\Games\db_tiendavirtual_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_tiendavirtual].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [db_tiendavirtual] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [db_tiendavirtual] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [db_tiendavirtual] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [db_tiendavirtual] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [db_tiendavirtual] SET ARITHABORT OFF 
GO

ALTER DATABASE [db_tiendavirtual] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [db_tiendavirtual] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [db_tiendavirtual] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [db_tiendavirtual] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [db_tiendavirtual] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [db_tiendavirtual] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [db_tiendavirtual] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [db_tiendavirtual] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [db_tiendavirtual] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [db_tiendavirtual] SET  ENABLE_BROKER 
GO

ALTER DATABASE [db_tiendavirtual] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [db_tiendavirtual] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [db_tiendavirtual] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [db_tiendavirtual] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [db_tiendavirtual] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [db_tiendavirtual] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [db_tiendavirtual] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [db_tiendavirtual] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [db_tiendavirtual] SET  MULTI_USER 
GO

ALTER DATABASE [db_tiendavirtual] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [db_tiendavirtual] SET DB_CHAINING OFF 
GO

ALTER DATABASE [db_tiendavirtual] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [db_tiendavirtual] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [db_tiendavirtual] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [db_tiendavirtual] SET QUERY_STORE = OFF
GO

USE [db_tiendavirtual]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [db_tiendavirtual] SET  READ_WRITE 
GO

